### ISSUE TITLE
Updater crashes on Windows 10 22H2

### ISSUE THREAD

**Issue by IrateRedKite** [Librelancer/Librelancer#175]
When attempting to update LancerEdit via the updater, I get the following error:

```
Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\Ruper\AppData\Local\Temp\tmpj544x0.tmp'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at LancerEdit.Updater.UpdateChecks.<>c__DisplayClass10_0.<Update>b__0()
   at LibreLancer.SDL2Game.Run(Game loop)
   at LibreLancer.Game.Run()
   at LancerEdit.Program.<>c__DisplayClass1_0.<Main>b__0()
   at LibreLancer.AppHandler.Run(Action action, Action onCrash)

Librelancer Version: 1cc4d7f-git (20241016)
```

This occurs immediately after the download is completed and seems to happen regardless of whether or not LancerEdit is run with elevated permissions.

**Comment by CallumDev** [comment]
Unfortunately this wasn't reproducible on my Win10 22H2 install.

An unrelated bug with the updater has been fixed, and a manual error dialog with advice to manually update has been implemented in [948c5ca](https://github.com/Librelancer/Librelancer/commit/948c5cad91653b919e46c667a1fccd22af1abe20) instead of hard crashing like this.

This will hopefully be something that solves itself over time, as plenty of false positive reports have been submitted to various vendors for the Librelancer SDK.
