### ISSUE TITLE
[Error] Engine: Librelancer has crashed

### ISSUE THREAD

**Issue by SashaRomanov** [Librelancer/Librelancer#75]
[Error] Engine: Librelancer has crashed. See the log for more information.
The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path)
   at LibreLancer.Data.SysFolder.WalkDir(String dir, Boolean recurse)
   at LibreLancer.Data.SysFolder..ctor(String path)
   at LibreLancer.Data.FileSystem.FromFolder(String folder, Boolean fastInit)
   at LibreLancer.GameDataManager..ctor(String path, ResourceManager resman)
   at LibreLancer.FreelancerGame.Load()
   at LibreLancer.Game.Run()
   at lancer.MainClass.<>c__DisplayClass0_0.<Main>b__0()
   at LibreLancer.AppHandler.Run(Action action, Action onCrash)

and on running ./server
Can't find librelancerserver.config.json

**Comment by CallumDev** [comment]
You'll need to run Librelancer.Launcher and point it to a Freelancer directory in order for the lancer binary to do anything. The server binary is not ready yet
