### ISSUE TITLE
Compressed cubemaps crash on startup

### ISSUE THREAD

**Issue by fkrauthan** [Librelancer/Librelancer#77]
I know this might not be supported but I have a Freelancer installation graphically adjusted based on this article (except the sweet FX step): https://www.reddit.com/r/freelancer/comments/2g93u6/2014_freelancer_graphics_mod_only_guide/

But when running Librelancer (I tried the official version `2019.08` and the latest full SDK) I get the following error after the launcher:

```
Compressed cubemaps
   at LibreLancer.TextureCube..ctor(Int32 size, Boolean mipMap, SurfaceFormat format)
   at LibreLancer.ImageLib.DDS.GetTextureCube(DDS_HEADER& header, BinaryReader reader)
   at LibreLancer.ImageLib.DDS.FromStream(Stream stream)
   at LibreLancer.Utf.Mat.TextureData.Initialize()
   at LibreLancer.GameResourceManager.AddTextures(TxmFile t, String filename)
   at LibreLancer.GameResourceManager.LoadResourceFile(String filename)
   at LibreLancer.GameData.ResolvedModel.LoadFile(ResourceManager res)
   at LibreLancer.Cutscene.AddEntities(ThnScript thn)
   at LibreLancer.Cutscene..ctor(ThnScriptContext context, GameDataManager gameData, Viewport viewport, Game game)
   at LibreLancer.LuaMenu..ctor(FreelancerGame g)
   at LibreLancer.LoadingDataState.<Update>b__6_0()
   at LibreLancer.GameState.DoFade(TimeSpan delta)
   at LibreLancer.LoadingDataState.Draw(TimeSpan delta)
   at LibreLancer.FreelancerGame.Draw(Double elapsed)
   at LibreLancer.Game.Run()
   at lancer.MainClass.<>c__DisplayClass0_0.<Main>b__0()
   at LibreLancer.AppHandler.Run(Action action, Action onCrash)
```

**Comment by CallumDev** [comment]
Fixed in 99157c3
