### ISSUE TITLE
lancer.exe crashes with error when clicking on owned ship in ship dealer in multiplayer

### ISSUE THREAD

**Issue by JimJamJamie** [Librelancer/Librelancer#86]
Steps to reproduce:

- Go to ship dealer
- Open sale window
- Click on your current ship
- lancer.exe will exit with the following error:

attempt to call a nil value
   at WattleScript.Interpreter.Execution.VM.Processor.Internal_ExecCall(Boolean canAwait, Int32 argsCount, Int32 instructionPtr, CallbackFunction handler, CallbackFunction continuation, Boolean thisCall, String debugText, DynValue unwindHandler)
   at WattleScript.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr, Boolean canAwait)
   at WattleScript.Interpreter.Execution.VM.Processor.Call_Internal(DynValue function, DynValue[] args, Boolean thisCall)
   at WattleScript.Interpreter.Script.Call(DynValue function, DynValue[] args)
   at WattleScript.Interpreter.Script.Call(DynValue function)
   at WattleScript.Interpreter.Script.Call(Object function)
   at WattleScript.Interpreter.Closure.Call()
   at LibreLancer.Interface.ListBox.<>c__DisplayClass23_0.<OnSelectedIndexChanged>b__0()
   at LibreLancer.Interface.ListBox.OnMouseClick(UiContext context, RectangleF parentRectangle)
   at LibreLancer.Interface.Panel.OnMouseClick(UiContext context, RectangleF parentRectangle)
   at LibreLancer.Interface.Panel.OnMouseClick(UiContext context, RectangleF parentRectangle)
   at LibreLancer.Interface.Panel.OnMouseClick(UiContext context, RectangleF parentRectangle)
   at LibreLancer.Interface.Panel.OnMouseClick(UiContext context, RectangleF parentRectangle)
   at LibreLancer.Interface.Container.OnMouseClick(UiContext context, RectangleF parentRectangle)
   at LibreLancer.Interface.Container.OnMouseClick(UiContext context, RectangleF parentRectangle)
   at LibreLancer.Interface.UiContext.OnMouseClick()
   at LibreLancer.Interface.UiContext.MouseOnMouseUp(MouseEventArgs e)
   at LibreLancer.Mouse.OnMouseUp(MouseButtons b)
   at LibreLancer.Game.Run()
   at lancer.MainClass.<>c__DisplayClass0_0.<Main>b__0()
   at LibreLancer.AppHandler.Run(Action action, Action onCrash)

Librelancer Version: ad316cb-git (20220930)

**Comment by CallumDev** [comment]
Good catch :)
