### ISSUE TITLE
Librelancer on Debian crashes after I select new game

### ISSUE THREAD

**Issue by aknight2015** [Librelancer/Librelancer#87]
I made both Launcher and lancer executable (chmod a+x) and it starts up just fine. I go to new game and it crashes to terminal.
` [Error] Engine: Librelancer has crashed. See the log for more information.
Specified argument was out of the range of valid values. (Parameter 'fieldOfView')
   at System.Numerics.Matrix4x4.CreatePerspectiveFieldOfView(Single fieldOfView, Single aspectRatio, Single nearPlaneDistance, Single farPlaneDistance)
   at LibreLancer.ChaseCamera.UpdateProjection()
   at LibreLancer.ChaseCamera.set_Viewport(Rectangle value)
   at LibreLancer.ChaseCamera..ctor(Rectangle viewport, CameraIni ini)
   at LibreLancer.SpaceGameplay.FinishLoad()
   at LibreLancer.SpaceGameplay.Update(Double delta)
   at LibreLancer.FreelancerGame.Update(Double elapsed)
   at LibreLancer.Game.Run()
   at lancer.MainClass.<>c__DisplayClass0_0.<Main>b__0()
   at LibreLancer.AppHandler.Run(Action action, Action onCrash)

Librelancer Version: 0bd1443-git (20221003) `

**Comment by CallumDev** [comment]
Can you tell me what resolution you're running the game at?

Also please tell me if this is a vanilla copy of Freelancer, particularly if the contents of `cameras.ini` have been modified from the defaults of `fovx = 70`

**Comment by CallumDev** [comment]
Most likely fixed in commit 2f23b6a
